django/django_2019/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

django/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:question_id>/corregir/', views.corregir, name='corregir'),
]

django/polls/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=100)
    pub_date = models.DateTimeField('fecha de publicacion')
    
    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
        was_published_recently.admin_order_field = 'pub_date'
        was_published_recently.boolean = True
        was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=100)
    correcto = models.BooleanField(default=False)


    def __str__(self):
        return self.choice_text

django/polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import Choice, Question
from django.http import HttpResponse
from django.template import loader
from django.http import Http404
from django.shortcuts import render

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
            ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def corregir(request, question_id):
	question = get_object_or_404(Question, pk=question_id)	
	opciones = question.choice_set.all()
	elegidas= question.choice_set.filter(pk__in=request.POST.getlist('choice'))
	c={} 
	for opcion in opciones:   
		if opcion.correcto :
			c[opcion]= opcion in elegidas
		else:
			c[opcion] = opcion not in elegidas
	return render(request,'polls/results.html',{'question': question, 'c': c})

'''
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
'''

django/polls/templates/polls/detail.html
{% load static %}
<h1>{{ question.question_text }}</h1>

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}"> 
<ul>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:corregir' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <li><input type="checkbox" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}"><p style="color:blue">{{ choice.choice_text  }}</label><br></p></li>
{% endfor %}
</ul>
<input type="submit" value="Vote">
</form>

django/polls/templates/polls/index.html
{% load static %}
{% if latest_question_list %}
<h1>
<strong>preguntas</strong>
</h1>

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
    <ul>
    {% for question in latest_question_list %}
      <li><a href="{% url 'polls:detail' question.id %}"> <p style="color:blue"><input type="submit" value="{{ question.question_text }}"></a></li></p>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

django/polls/templates/polls/results.html
{% load static %}
<h1>{{ question.question_text }}</h1>
<li>RESPUESTAS</li>
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
<ul>
{% for opcion,resultado in c.items %} 
	<li>{{ opcion }} {{resultado}} {% if opcion.correcto %}
<p style="color:green"> correcto </p>
		{%else%}
<p style="color:red"> incorrecto </p>
        {%endif%}
    </li>
{% endfor %}
</ul>
<a href="{% url 'polls:detail' question.id %}"><input type="submit" value="Volver a votar"></a>